name: Run Python Script and Upload File

on:
  #push:
  #  branches:
  #    - main
  workflow_dispatch:
  schedule:
    - cron: '0 17 * * *'  # Chạy script mỗi 12 giờ

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
  
    - name: Install expect
      run: sudo apt-get install -y expect

    - name: Run Python script
      run: python get_shows.py > script.log

    - name: Upload via SFTP
      run: |
        echo "
        spawn sftp -oPort=2022 -o StrictHostKeyChecking=no 336004465872207872.47485564@rycell.sillydevelopment.co.uk
        expect \"password:\"
        send \"+310101-\r\"
        expect \"sftp>\"
        send \"put shows.json\r\"
        expect \"sftp>\"
        send \"bye\r\"
        " > sftp_script.exp
        expect -f sftp_script.exp
