name: Run Python Script and Upload File

on:
  push:
    branches:
      - main  # Thay 'main' bằng tên nhánh bạn muốn chạy GitHub Action khi có code được push lên
  workflow_dispatch:
  schedule:
    - cron: '0 0,12 * * *'  # Chạy script mỗi 24 giờ (vào nửa đêm)

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Thay '3.x' bằng phiên bản Python bạn muốn

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  # Nếu bạn có requirements.txt

    - name: Run Python script
      run: python get_shows.py  # Chạy script của bạn

    - name: Upload via SFTP
      run: |
        echo "put shows.json" > sftp_commands.txt
        sshpass -p 'uyucnVw1fWpJlp8' sftp -oPort=2022 -b sftp_commands.txt 336004465872207872.543fff0b@fi6.bot-hosting.net

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: script-log
        path: script.log

