name: Run Python Script and Upload File

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 5,17 * * *'  # Chạy script mỗi 12 giờ

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Cache apt packages
      uses: actions/cache@v3
      with:
        path: /var/cache/apt
        key: ${{ runner.os }}-apt-${{ hashFiles('**/get_shows.py') }}
        restore-keys: |
          ${{ runner.os }}-apt-

    - name: Install expect
      run: sudo apt-get update && sudo apt-get install -y expect

    - name: Run Python script
      run: python get_shows.py

    - name: Upload via SFTP
      run: |
        echo "
        spawn sftp -oPort=2022 -o StrictHostKeyChecking=no 336004465872207872.543fff0b@fi6.bot-hosting.net
        expect \"password:\"
        send \"1YILAlkCBHfTag9\r\"
        expect \"sftp>\"
        send \"put shows.json\r\"
        expect \"sftp>\"
        send \"bye\r\"
        " > sftp_script.exp
        expect -f sftp_script.exp

    - name: Upload log file
      uses: actions/upload-artifact@v3
      with:
        name: script-log
        path: script.log

